management:
    resource: "@ManagementBundle/Controller/"
    type:     annotation
    prefix:   /admin

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

studynco:
    resource: "@StudyncoBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin

posts:
    type:     annotation
    resource: StudyncoBundle\Controller\PostController
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

